### ISSUE TITLE
ABI error - fixed in eosjs@16.0.5 but not working with scatter

### ISSUE THREAD

**Issue by Dylan-Phoon** [GetScatter/ScatterWebExtension#155]
When I try to push this transaction: 
```javascript
const eos = scatter.eos(...options)

eos.transaction(
{
  actions: [
  {
  account: "mycontract",
  name: "makewithdraw",
  authorization: [{
    actor: "myaccount",
    permission: 'active'
  }],
  data: {
    withdraw_account: "myaccount" //Type: account_name
    target_token_contract: "gemtoken", //Type: string
    amount_of_token: "1.0000 GEM"  //Type: asset
}
  }
  ]
})

```
I get this error:
```
Error: [
    "Missing float32 in make_order.fields.price",
    "Missing float32 in order.fields.price"
]
    at e.exports (inject.js:34) //The inject.js links to scatter here: chrome-extension://ammjpmhgckkpcamddpolhchgomcojkle/inject.js
    at u (inject.js:57)
    at inject.js:57
```

The original error can be found here: https://github.com/EOSIO/eosjs/issues/309
Which gave the same error but in a different place at eos.min.js:
```
Error: [
    "Missing float32 in make_order.fields.price",
    "Missing float32 in order.fields.price"
]
    at M.exports (eos.min.js:1) //Note: The different file
    at i (eos.min.js:1)
    at eos.min.js:1
```
After eosjs@16.0.5 the error above^ no longer exists. When I try to make the same transaction but with eosjs and keyProvider it works fine. Only getting the error now when I try to do a transaction when using eosjs with scatter.

**Comment by nsjames** [comment]
Hmm, I might just need to update the `eosjs` inside of Scatter itself. I'll update to chrome store soon and ping this ticket so we can see if it fixes that.

**Comment by nsjames** [comment]
Updated on chrome store.

**Comment by Dylan-Phoon** [comment]
Previous error has gone but now I'm getting this error instead: 

```javascript
l.AssertionError {name: "AssertionError", actual: undefined, expected: true, operator: "==", message: "missing type or struct: makewithdraw", …}
actual: undefined
expected: true
generatedMessage: false
message: "missing type or struct: makewithdraw"
name: "AssertionError"
operator: "=="
stack: "AssertionError: missing type or struct: makewithdraw↵    at Object.fromBuffer (chrome-extension://ammjpmhgckkpcamddpolhchgomcojkle/inject.js:34:107716)↵    at A.Promise.all.e.transaction.actions.map (chrome-extension://ammjpmhgckkpcamddpolhchgomcojkle/inject.js:40:271265)↵    at Array.map (<anonymous>)↵    at A (chrome-extension://ammjpmhgckkpcamddpolhchgomcojkle/inject.js:40:271209)"
```

**Comment by okayplanet** [comment]
Great news!  I am having a similar issue:

```
    return {
      actions: [{
        account: this.config.code.recurringpay,
        name: 'withdraw',
        authorization: [{
          actor: _from,
          permission: _permission
        }],
        data: {
          owner: _from,
          contract: _contract,
          quantity: _quantity
        }
      }]
    }
```

And the error is:
```
Uncaught (in promise) Error: [
    "Missing float32 in raw_token_service_stat.fields.percentage_fee",
    "Missing float32 in token_service_stat.fields.percentage_fee"
]
    at module.exports (_property-desc.js:9)
    at abi (_hide.js:9)
    at _hide.js:9
```
